### ISSUE TITLE
paper哪里下载

### ISSUE THREAD

**Issue by zg9uagfv** [WeitaoVan/faceID#1]
你好
论文《OCCLUSION ROBUST FACE RECOGNITION BASED ON MASK LEARNING》哪里可以下载？

**Comment by WeitaoVan** [comment]
I haven't uploaded the paper to arxiv yet. You can download the paper in BaiduYun.
https://pan.baidu.com/s/1skEjYGX 
code: yngr
This link is valid within 7 days.

**Comment by JoyLuo** [comment]
Dear WeitaoVan:
  the link you posted is invalid. 
  how to down your paper《OCCLUSION ROBUST FACE RECOGNITION BASED ON MASK LEARNING》lately?

**Comment by WeitaoVan** [comment]
@JoyLuo 
You can download it from https://pan.baidu.com/s/1qXEr5KC

**Comment by JoyLuo** [comment]
@WeitaoVan 
  I have down it form the web link you posted, thanks.

**Comment by JoyLuo** [comment]
@WeitaoVan 
  I have down the paper form the link you posted. thanks.
